// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Join Discord', href: 'https://osc.toys/discord', className: 'discordSidebar'}
  ],
};

module.exports = sidebars;
